version: '2'
services:
    edde-js:
        container_name: edde-js
        hostname: edde-js-local
        image: edde-js:local
        environment:
            - NODE_ENV=development
            - NPM_TOKEN=${NPM_TOKEN}
        volumes:
            - ../:/edde-js
